services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=http://localhost:8080/
      - SEARXNG_API_KEY=easykey
    volumes:
      - ./searxng-settings:/etc/searxng

  webtools:
    image: vasthana/webtools:v1
    container_name: webtools
    ports:
      - "8000:8000"
    depends_on:
      - searxng
    environment:
      - OPENAI_API_KEY=
      - GOOGLE_API_KEY=
      - OLLAMA_URL=
      - GROQ_API_KEY=
      - SEARCH_URL=http://searxng:8080/search
      - EXTRACTION_MODEL=
      - NUMBER_OF_POINTS=
      - use_ollama=False
      - use_openai=True
      - use_groq=False
      - TTL_CACHE=300
      - SEARXNG_API_KEY=easykey
